/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_umich_eecs_twatchp_AutoTuner */

#ifndef _Included_edu_umich_eecs_twatchp_AutoTuner
#define _Included_edu_umich_eecs_twatchp_AutoTuner
#ifdef __cplusplus
extern "C" {
#endif
#undef edu_umich_eecs_twatchp_AutoTuner_MAXATTEMPTS
#define edu_umich_eecs_twatchp_AutoTuner_MAXATTEMPTS 15L
/*
 * Class:     edu_umich_eecs_twatchp_AutoTuner
 * Method:    findchirps
 * Signature: ([D[D[D[IIIII)I
 */
JNIEXPORT jint JNICALL Java_edu_umich_eecs_twatchp_AutoTuner_findchirps
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jdoubleArray, jintArray, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
